Schools = new Mongo.Collection('schools')
TatResults = new Mongo.Collection('TatResults')
Teachers = new Mongo.Collection('teachers')
Subjects = new Mongo.Collection('subjects')
TatCombinedRes = new Mongo.Collection('TatCombinedResults')
BtsRatings = new Mongo.Collection('BtsRatings')
